title: "Terapia Liberal"
description: "Análisis independiente sobre economía, geopolítica y filosofía liberal"
url: "https://terapialiberal.netlify.app"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  posts:
    output: true
    permalink: /articles/:slug/
    path: "articles"

future: true
keep_files: ["data", "css", "js", "images", "admin", "articles/*.html"]
